/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

// define GPIO values
#define GPIO_A				0x40020000
#define GPIO_C 				0x40020800
#define GPIO_B				0x40020400
#define SYSCFG 				0x40013800

// define timers and RCC
#define RCC 				0x40023800
#define TIM12				0x40001800

// define EXTI and NVIC values
#define EXTI 				0x40013C00
#define NVIC_ISER_0			0xE000E000

// define offsets
#define RCC_AHB1_ENR_offset 0x30
#define RCC_APB1_ENR_offset 0x40
#define RCC_APB2_ENR_offset 0x44
#define EXTI_IMR_offset 	0x0
#define EXTI_RTSR_offset 	0x08
#define EXTI_FTSR_offset 	0x0C
#define NVIC_ISER_1_offset	(0x100 + 0x04)
#define NVIC_ISPR_1_offset	(0x200 + 0x04)
#define NVIC_ICPR_1_offset	(0x280 + 0x04)
#define EXTI_PR_offset		0x14

// define timer offsets
#define TIM12_CR1_offset	0x00
#define TIM12_DIER_offset	0x0C
#define TIM12_SR_offset		0x10
#define TIM12_CNT_offset	0x24
#define TIM12_PSC_offset	0x28
#define TIM12_ARR_offset	0x2C

#define TIM12_CR1			(*(volatile uint32_t*) (TIM12 + TIM12_CR1_offset))
#define TIM12_DIER			(*(volatile uint32_t*) (TIM12 + TIM12_DIER_offset))
#define TIM12_SR			(*(volatile uint32_t*) (TIM12 + TIM12_SR_offset))
#define TIM12_CNT			(*(volatile uint32_t*) (TIM12 + TIM12_CNT_offset))
#define TIM12_PSC			(*(volatile uint32_t*) (TIM12 + TIM12_PSC_offset))
#define TIM12_ARR			(*(volatile uint32_t*) (TIM12 + TIM12_ARR_offset))

// define GPIO A registers
#define GPIO_A_MODER	(*(volatile uint32_t*) GPIO_A)
#define GPIO_A_BSRR		(*(volatile uint32_t*) (GPIO_A + 0x14))
#define GPIO_A_ODR		(*(volatile uint32_t*) (GPIO_A + 0x18))

// define GPIO B registers
#define GPIO_B_MODER	(*(volatile uint32_t*) GPIO_B)
#define GPIO_B_AFRH 	(*(volatile uint32_t*) (GPIO_B + 0x24))

// define GPIO C registers
#define GPIO_C_MODER 	(*(volatile uint32_t*) GPIO_C)
#define GPIO_C_PUPDR 	(*(volatile uint32_t*) (GPIO_C + 0x0C))
#define GPIO_C_IDR   	(*(volatile uint32_t*) (GPIO_C + 0x10))

// define EXTI
#define SYSCFG_EXTICR4	(*(volatile uint32_t*) (SYSCFG + 0x14))
#define EXTI15_10 		(*(volatile uint32_t*) 0x000000E0)
#define EXTI_IMR 		(*(volatile uint32_t*) (EXTI + EXTI_IMR_offset))
#define EXTI_RTSR		(*(volatile uint32_t*) (EXTI + EXTI_RTSR_offset))
#define EXTI_FTSR		(*(volatile uint32_t*) (EXTI + EXTI_FTSR_offset))
#define NVIC_ISER_1		(*(volatile uint32_t*) (NVIC_ISER_0 + NVIC_ISER_1_offset))

// define NVIC for TIM12
#define NVIC_ISPR_1		(*(volatile uint32_t*) (NVIC_ISER_0 + NVIC_ISPR_1_offset))
#define NVIC_ICPR_1		(*(volatile uint32_t*) (NVIC_ISER_0 + NVIC_ICPR_1_offset))


// define RCC
#define RCC_APB1_EN 	(*(volatile uint32_t*) (RCC+RCC_APB1_ENR_offset))
#define RCC_AHB1_EN 	(*(volatile uint32_t*) (RCC+RCC_AHB1_ENR_offset))
#define RCC_APB2_EN 	(*(volatile uint32_t*) (RCC+RCC_APB2_ENR_offset))
#define EXTI_PR			(*(volatile uint32_t*) (EXTI + EXTI_PR_offset))



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint32_t press_counter = 0;
volatile uint32_t timer_counter = 0;

void EXTI15_10_IRQHandler(void) {
	if (EXTI_PR & (1U << 13)) {
		EXTI_PR = (1U <<13);
		press_counter = (press_counter + 1) % 3;
	}
}

void turn_LD2_off(void) {
	GPIO_A_BSRR |= (0x1U << 21);
}

void turn_LD2_on(void) {
	GPIO_A_BSRR |= (0x1U << 5);
}

void toggle_LD2(void) {
	// if the value at the LEDregister is 1 --> resets the bit

	if (press_counter == 2) {
		if (GPIO_A_ODR & (0x1U<<5)) {
			turn_LD2_off();
		}
		else { //if the value at the LED register is 0 --> sets the bit
			turn_LD2_on();
		}
	}
}

void TIM8_BRK_TIM12_IRQHandler(void){
	if (TIM12_SR & (1U << 0)) {
		timer_counter = (timer_counter + 1) % 3;

		if (timer_counter == 2) {
			toggle_LD2();
		}

		NVIC_ICPR_1 |= (1U << 11);
		TIM12_SR &= ~(1U << 0);
	}
}

void GPIO_A_setup(void) {

	//set up GPIO_A pin for LED
	GPIO_A_MODER &= ~(3U<<10);
	GPIO_A_MODER |= (1U<<10);
}

void GPIO_B_setup(void) {

	// set up GPIO pin for timer
	GPIO_B_MODER &= ~(3U<<30);
	GPIO_B_MODER |= (2U<<30);

	// set up AF mode
	GPIO_B_AFRH &= ~(0xFU<<28);
	GPIO_B_AFRH |= (0x9U<<28);
}

void GPIO_C_setup(void) {
	// set up GPIO_C pin
	GPIO_C_MODER &= ~(3U<< 26);

	// set up input mode for the GPIOC, pin 13
	GPIO_C_PUPDR |= (1U << 26);
}

// turn on RCC
void RCC_setup(void) {
	// turn on RCC for button and LED
	RCC_AHB1_EN |= (1U << 2);
	RCC_AHB1_EN |= (1U << 0);

	// enable RCC for TIM12
	RCC_APB1_EN |= (1U << 6);

	//enable RCC for SYSCFG
	RCC_APB2_EN |= (1U << 14);
}

void setup_NVIC_EXTI(void) {
	// configure EXTI line
	EXTI_IMR |= (1U << 13);
	EXTI_FTSR |= (1U << 13);

	// configure EXTI control register
	SYSCFG_EXTICR4 &= ~(0xFU << 4);
	SYSCFG_EXTICR4 |= (1U << 5);

	// set up NVIC
	NVIC_ISER_1 |= (1U << 8);
}

void TIM12_setup(void) {
	// clear the TIM12 control register
	TIM12_CR1 &= ~(0x1U << 7);
	TIM12_CR1 &= ~(0x1U << 0);

	//set up TIM12 CR register
	TIM12_CR1 |= (0x1U << 7);
	TIM12_CR1 |= (0x1U << 0);

	// set up the DIER
	TIM12_DIER &= ~(0x1U << 0);
	TIM12_DIER |= (0x1U << 0);
	// we need to read from TIM12_SR to get update interrupt event
	TIM12_PSC = 1600 - 1;
	TIM12_ARR = 1000 - 1;
}

void setup_NVIC_TIM12(void) {
	NVIC_ISER_1 |= (0x1 << 11);
}

int main(void)
{
	// begin setup
	RCC_setup();
	// resetting BR5 register
	GPIO_A_BSRR |= (0x1U << 5);
	GPIO_A_setup();
	GPIO_B_setup();
	GPIO_C_setup();
	setup_NVIC_EXTI();
	TIM12_setup();
	setup_NVIC_TIM12();

	turn_LD2_off();
	turn_LD2_on();

    /* Loop forever */
	while (1) {
		switch(press_counter) {
		case 0:
			turn_LD2_off();
			break;
		case 1:
			turn_LD2_on();
			break;
		case 2:
			break;
		}
	}
}
